name: test release
run-name: ${{ github.actor }}'s patch
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-24.10
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '14'
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --release --no-default-features