name: test serde
run-name: ${{ github.actor }}'s patch
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-24.10
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          cache: true
          toolchain: nightly
      - run: |
          cargo test --no-default-features --features=serde
          cargo test --no-default-features --features=serde,std
          cargo test --no-default-features --features=schemars
